module.exports = {
    NO_RESULTS_FOUND : 0,
    SUCCESSFULL_SEARCH : 1,
    SUCCESSFULL_REGISTER_OR_LOGIN : 2,
    SUCCESS_UPDATE : 3,
    SUCCESS_DELETE : 4,
    INVALID_PARAMETERS : -1,
    UNSUCCESSFULL_REGISTER_OR_LOGIN : -2,
    UNSUCCESS_UPDATE : -3,
    UNSUCCESS_DELETE : -4,
};